spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/sample?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: c05853yy
    driverClassName: com.mysql.jdbc.Driver
    